name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    container: gcc:latest

    steps:
    - uses: actions/checkout@v2
    - name: version check
      run: g++ --version && clang++ --version
    - name: make
      run: make
