name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    container: gcc:latest

    steps:
    - uses: actions/checkout@v2
    - name: prepare
      run: |-
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt install gcc-10 g++-10 libc++-dev libc++abi-dev
    - name: version check
      run: g++-10 --version && clang++ --version
    - name: make
      run: make
