name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-20.04
    container: gcc:latest
    steps:
    - uses: actions/checkout@v2
    - name: version check
      run: g++ --version
    - name: make
      run: make
