name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build-gcc:
    runs-on: ubuntu-20.04
    container: gcc:latest
    steps:
    - uses: actions/checkout@v2
    - name: version check
      run: g++ --version
    - name: make
      run: make gcc
  build-clang:
    runs-on: ubuntu-20.04
    container: rsmmr/clang:9.0
    steps:
    - uses: actions/checkout@v2
    - name: version check
      run: clang++ --version
    - name: make
      run: make
